FROM node:14 as builder
ENV NODE_ENV=production
# to change
USER root 
WORKDIR /deploy
COPY . ./
RUN npm install -g @microsoft/rush
RUN rush -h
RUN rush install
RUN rush build

# production environment
FROM nginx:stable-alpine
WORKDIR /deploy
COPY --from=builder /app/common/deploy/apps/web/build ./web
RUN ls -la
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]